### ISSUE TITLE
Error with CsvHelper

### ISSUE THREAD

**Issue by klacol** [CodeCavePro/revit-toolkit#10]
Hi, great Tool here.

With CodeCave.Revit.Toolkit.2017.2.11 we get this error in the Constructor of the SPF:

```
SharedParameterFile sharedParamFile = new SharedParameterFile("abc");
```

> MissingMethodException: Method not found: "Void CsvHelper.Configuration.Configuration.set_QuoteNoFields(Boolean)".

**Comment by salaros** [comment]
@klacol first of all thanks complimenting the library, you could star it, so more people could know about it.

I tried to reproduce your issue, but I haven't managed to do so. I've even created a test for your case and it now intentionally fails, but for a different reason.
https://github.com/CodeCavePro/revit-toolkit/blob/master/tests/SharedParameterFileTests.cs#L368

Please tell me more on .NET Core / Framework version you are using etc, so I could reproduce the issue.

**Comment by klacol** [comment]
@salaros : I cannot reproduce the error myself. I think, I have been shortly in the dependency hell and found a way out.

**Comment by salaros** [comment]
@klacol If you have any feature request in mind or encounter any bug - please do not hesitate to open another issue here. Have a nice day!
