### ISSUE TITLE
Can i convert rvt to ifc without Revit by this?

### ISSUE THREAD

**Issue by Febfire** [CodeCavePro/revit-toolkit#9]
Can i convert rvt to ifc without Revit by this?
thanks in advance.

**Comment by salaros** [comment]
Hey @Febfire, I appreciate your interest in this library. Unfortunately .rfa/.rft and .rvt/.rte and other Revit files are encrypted and the format is closed and undocumented, just like it was with DWG file in the past, before the latter was reverse-engineered.
Therefore the internals of Revit files can't be read outside Revit. However [Teigha BIM](https://www.opendesign.com/products/bim) project has done some progress in that direction, however from what I know it's not a production grade tool, it's still in alpha / beta

So you might use Teigha BIM to read .rvt files and then [IFC SDK](https://github.com/jmirtsch/GeometryGymIFC) to persist the geometry to an .ifc file

Good luck with your project

P.S. RevitLESS toolkit can read some metadata from OLE storage inside Revit files, soon I will add some additional XML metadata parsing, but it mostly about shared parameter and type catalog file manipulation without Revit, which is still useful in many cases

**Comment by danielkrajnik** [comment]
hooly cow that's so bad - How much would it cost to reverse engineer rvt files?

**Comment by salaros** [comment]
@danielkrajnik it was already done by ODA - https://www.opendesign.com/products/bimrv
Licenses are pricey, but it's great, because you can do a lot of things with it

**Comment by danielkrajnik** [comment]
@salaros hmm "out of the frying pan into the fire". But at least it is possible! I assume it's legal, because... clean-room method? thanks a lot for mentioning that though. Do you know about any other similar projects?

**Comment by salaros** [comment]
No, I think they are the only one who did reverse engineering.
There is also [Forge API](https://forge.autodesk.com/en/docs/) from Autodesk which is a SaaS, it allows you to process Revit and other formats in the cloud.
Please contact me at salaros@salaros.com I can describe other, less conventional, scenarios

![image](https://user-images.githubusercontent.com/675348/111628699-8e610580-8801-11eb-997f-9a3f9139f5ba.png)
